repos:
- repo: git://github.com/pre-commit/mirrors-isort
  sha: 'v4.2.15'
  hooks:
  - id: isort
    args:
      - --check-only
      - --recursive
      - --settings-path
      - ./setup.cfg
      - .
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.1
  hooks:
  - id: flake8
    args:
      - --ignore=E501,F401,E128,E402,E731,F821