sudo: false
language: python
python:
  - "3.6"
env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/codesponsor/"
install:
  - "pip install pipenv"
  - "cp code_sponsor/.env-sample code_sponsor/.env"
  - "pipenv install --dev"
test:
  - "pipenv run python manage.py test"