# Generated by Django 2.0.1 on 2018-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
