# Generated by Django 2.0.1 on 2018-01-22 16:31

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', netfields.fields.InetAddressField(max_length=39)),
                ('user_agent', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sponsor')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sponsorship')),
            ],
        ),
    ]
